Month 10/step 1
TimBearWeiss/react_burger pull request #7
Opened 2023-02-28 12:43 UTC by TimBearWeiss

2023-02-28 15:23 UTC, randomroot requested changes
**Доброго времени суток!** ☀️ 🌙 

Вы проделали хорошую работу по типизации вашего проекте, однако, для успешной сдачи работы вам необходимо внимательно ознакомиться с комментариями, оставленными в рамках ревью и провести необходимые **изменения**, обратив особое внимание на следующие моменты:

- Следует типизировать **файлы** `api.js` и `data.js`;
- Следует типизировать **хук** `useDispatch` и отказаться от использования `any` для переменной `dispatch`;
- Использование типа `any` в большинстве случае **нецелесообразно**, т.к. этот подход не позволяет анализатору кода своевременно проверять его на ошибки, которые могут быть выявлены на этапе сборки проекта и усложняет вашу работу с кодом, т.к. значения будут неочевидными (см. https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#any)
- Наименование типов следует приводить к стилю `TCamelCase`, т.к. `T` - это префикс

Также, в рамках ревью были предложены **улучшения** вашего кода, которое могут повысить его качество, исправить возможные проблемы в будущем и углубить ваше значение по курсу.

---

Перед повторной сдачей, пожалуйста, убедитесь в том, что проект работает **корректно** и **полностью**, согласно условиям задания и чек-листу, а в консоли браузера и в консоли вашей IDE **нет ошибок** и присутствует **минимально** возможное кол-во **предупреждений**. Работа будет принята **только** после исправления всех комментариев с меткой "Надо исправить". 

---

**Успешного вам рефакторинга, хорошего настроения и отличного дня!** 🐈

2023-02-28 15:23 UTC, randomroot commented on src/services/reducers/wsReducer.ts
> +  wsConnected: Boolean;
🟡 **Можно улучшить:**

В данном случае можно использовать простой тип `boolean`, вместо обертки `Boolean`

2023-02-28 15:23 UTC, randomroot commented on src/services/reducers/burgerConstructor.ts
> +  constructorBuns: any;
🔴 **Нужно исправить:**

Следует задать конкретный тип для данного ключа, в данном случае целесообразно использовать `TIngredient`

2023-02-28 15:23 UTC, randomroot commented on src/services/middleware/wsMiddleware.ts
> +    return (next: any) => (action: any) => {
🟡 **Можно улучшить:**

Рассмотрите возможность использования типа `Middleware<{}, RootState>` для `sockerMiddleware`, чтобы уменьшить использование количества `any`

2023-02-28 15:23 UTC, randomroot commented on src/services/actions/order.ts
> +type TgetOrderRequest = {
🔴 **Нужно исправить:**

Наименование типов следует приводить к стилю `TCamelCase`, т.к. `T` - это префикс

2023-02-28 15:23 UTC, randomroot commented on src/services/actions/ingredients.ts
> +// export const getAllIngredients: AppThunk = () => {
🟡 **Можно улучшить:**

Неиспользуемый код имеет смысл удалять из файлов, чтобы поддерживать чистоту кода. В случае необходимости его восстановления можно воспользоваться средствами Git-a.

2023-02-28 15:23 UTC, randomroot commented on src/services/actions/burgerConstructor.ts
> +type itemCard = {
🔴 **Нужно исправить:**

Наименование типов следует привести к виду `TCamelCase`

2023-02-28 15:23 UTC, randomroot commented on src/pages/RegisterPage.tsx
> +const RefisterPage = () => {
🟡 **Можно улучшить:**

Допущена орфографическая ошибка

2023-02-28 15:23 UTC, randomroot commented on src/components/BurgerIngredients/BurgerIngredients.tsx
> +    let test = document.querySelector<any>(`#${value}`);
🟡 **Можно улучшить:**

1) Переменная является константой, поэтому имеет смысл заменить `let` на `const`;
2) Вместо `any` лучше использовать простой `HTMLElement`, а ниже воспользоваться оператором `?.`, чтобы не возникало ошибок на случай, если элемента не окажется на экране

2023-02-28 15:23 UTC, randomroot commented on src/components/CurrentOrderInModal/CurrentOrderInModal.tsx
> +    <>
🟡 **Можно улучшить:**

Использование `React.Fragment` в данном случае не требуется, т.к. `<div>` ниже оборачивает весь компонент :)

2023-02-28 15:23 UTC, randomroot commented on src/components/CurrentOrderInModal/CurrentOrderInModal.tsx
> +  const allOrders = useTypedSelector((store: any) => store.orderFeed.allOrders);
🔴 **Нужно исправить:**

Использование `any` в данном случае не целесообразно, т.к. хук уже даёт вам необходимую типизацию

2023-02-28 15:23 UTC, randomroot commented on src/components/CurrentOrderInModal/CurrentOrderInModal.tsx
> +  const currentOrder = allOrders.find((item: TIngredient) => item._id === id);
🔴 **Нужно исправить:**

Для `item` задан некорректный тип, т.к. поиск осуществляется среди заказов, а в типе - ингредиент

2023-02-28 15:23 UTC, randomroot commented on src/components/InfoOrder/InfoOrder.tsx
> +    const newArray: any = [];
🔴 **Нужно исправить:**

Для данного массива следует задать конкретную типизацию (в данном случае это список `TIngredient`)

2023-02-28 15:23 UTC, randomroot commented on src/components/OrderListElement/OrderListElement.tsx
> +    let newArray: any = [];
🔴 **Нужно исправить:**

Для данного массива следует задать конкретную типизацию (в данном случае это список `TIngredient`)

2023-02-28 15:23 UTC, randomroot commented on src/components/OrderListElement/OrderListElement.tsx
> +  item: any;
🔴 **Нужно исправить:**

Для данного ключа следует задать конкретную типизацию

2023-02-28 15:23 UTC, randomroot commented on src/components/ProtectedRouteElement/ProtectedRouteElement.tsx
> +  children: any;
🔴 **Нужно исправить:**

Для данного массива следует задать конкретную типизацию (в компонентов есть специальный тип `ReactElement`)

2023-02-28 15:23 UTC, randomroot commented on src/components/StoryList/StoryList.tsx
> +  allOrders: any;
🔴 **Нужно исправить:**

Для данного массива следует задать конкретную типизацию (в данном случае это список заказов)

2023-02-28 15:23 UTC, randomroot commented on src/pages/CurrentOrderPage.tsx
> +    (previous: number, current: any) => previous + current.price,
🔴 **Нужно исправить:**

Для данного элемента следует задать конкретную типизацию (в данном случае это `TIngredient`)

2023-02-28 15:23 UTC, randomroot commented on src/pages/CurrentOrderPageProfile.tsx
> +    (previous: number, current: any) => previous + current.price,
🔴 **Нужно исправить:**

Для данного элемента следует задать конкретную типизацию (в данном случае это `TIngredient`)

2023-03-03 07:34 UTC, randomroot requested changes
**Здравствуйте!**

Вы успешно внесли множество изменений и улучшений в ваш проект, так держать, однако остались несколько моментов, которые следует также исправить для сдачи проекта в данном спринте:

- Следует исправить все моменты, отмеченные в рамках предыдущего ревью;
- Следует улучшить типизацию функции `checkResponse`, добавив ей возможность возвращать конкретный тип, вместо `any` (подробнее в комментариях);
- Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс;

**Хорошего вам дня и настроения!** 🐈

2023-03-03 07:34 UTC, randomroot commented on src/utils/api.ts
> +function checkResponse(res: any) {
🔴 **Нужно исправить:**

В текущем виде функция `checkResponse` не конкретизирует тип возвращаемого значения в теле ответа, поэтому все последующие функции связанные с ней работают с `any`, что не позволяет TypeScript отследить корректность вашего кода:

![image](https://user-images.githubusercontent.com/15111821/222655402-ee586b45-642c-4851-8072-c5bad5c19674.png)

**Чтобы улучшить данную ситуацию** вы можете воспользоваться следующим подходом:

На основе всех ответов из API вашего бэкенда вы можете обратить внимание, что они имеют схожую структуру с полем `success`, поэтому воспользовавшись пересечением типов получим универсальную структуру:

```typescript
type TResponse<T> = {
  success: boolean;
} & T;
```

где `T` - тип, в котором описаны остальные ключи запроса, например `{ accessToken: string, refreshToken: string }`, которую можно использовать в функции проверки успешности и вернуть назад конкретный тип, в случае успеха:

```typescript
const checkResponse = <T>(res: Response) => {
  return res.ok ? res.json().then(data => data as TResponse<T>) : Promise.reject(res.status);
};
```
А затем применить её на ваши методы, связанные с вызовом API, создав для каждого из них (за исключением схожих) типы результатов и передав эти типы в функцию `checkResponse`. И тогда в других функциях, где будут вызывать данные методы вы получите правильный тип и валидацию вашего кода:

![image](https://user-images.githubusercontent.com/15111821/222458869-af3604af-61f4-478d-8d5a-fd369865f663.png)

2023-03-03 07:34 UTC, randomroot commented on src/utils/cookie.ts
> +function setCookie(name: string, value: string, props?: any) {
🟡 **Можно улучшить:**

Тип для параметра `props` можно задать следующим образом, с учётом возможных значений:

```jsx
props: { [key: string]: string | number | Date | boolean } = {}
```

2023-03-03 07:34 UTC, randomroot commented on src/utils/cookie.ts
> +  let matches = document.cookie.match(
🟡 **Можно улучшить:**

Т.к. значение переменной не изменяется далее в коде, то её можно сделать константой `const`.

2023-03-03 07:34 UTC, randomroot commented on src/services/actions/order.ts
> +export const getOrder: AppThunk = (IdIngredients: Array<string>) => {
🔴 **Нужно исправить:**

Наименования параметра следует привести к формату `camelCase`

2023-03-03 07:34 UTC, randomroot commented on src/services/actions/user.ts
> +type TregisterUserRequest = {
🔴 **Нужно исправить:**

**Здесь и ниже:**
Наименование типов следует приводить к стилю `TCamelCase`, т.к. `T` - это префикс

2023-03-03 07:34 UTC, randomroot commented on src/pages/ForgotPasswordPage.tsx
> +    console.log(e);
🟡 **Можно улучшить:**

Целесообразно убрать логгирование, используемое на этапе разработки и отладки, чтобы уменьшить кол-во информации, которое выводится в консоль

2023-03-03 07:34 UTC, randomroot commented on src/components/InfoOrderStory.jsx/InfoOrderStory.tsx
> +    {
🟡 **Можно улучшить:**

Имеет смысл убрать лишнюю вложенность

2023-03-03 07:34 UTC, randomroot commented on src/components/InfoOrderStory.jsx/InfoOrderStory.tsx
> +    let newArray: any = [];
🟡 **Можно улучшить:**

Т.к. значение переменной не изменяется далее в коде, то её можно сделать константой `const`. Изменение значений массива или объекта не считается изменением переменной

🔴 **Нужно исправить:**

Следует задать конкретный тип для данной переменной

2023-03-03 07:34 UTC, randomroot commented on src/pages/CurrentOrderPageProfile.tsx
> +        <div style={{ maxWidth: "640px", marginTop: "120px" }}>
🔴 **Нужно исправить:**

**Здесь и далее по коду:**
Инлайновые стили следует использовать только в крайних случаях, когда другими методами не получается задать стилизацию объекта, следует перенести такие стили в CSS файлы в отдельные классы и задавать именно имя класса в пропс.

2023-03-03 12:44 UTC, TimBearWeiss commented on src/components/InfoOrder/InfoOrder.tsx
> +    const newArray: any = [];
Когда ставлю нужную `типизацию` вылетает ошибка, которую не понимаю как исправить `TS2345: Argument of type 'TIngredient | undefined' is not assignable to parameter of type 'TIngredient'.
  Type 'undefined' is not assignable to type 'TIngredient'.
    31 |
    32 |     item.ingredients.forEach((e: string) => {
  > 33 |       newArray.push(allIngredients.find((element) => element._id === e));
       |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    34 |     });`

2023-03-05 15:29 UTC, randomroot approved these changes
🟢 **Работа принята:**

Все необходимые правки были внесены, код улучшен согласно рекомендациям, критических замечаний больше не имеется, **так держать**👍

Отличная работа, **желаю вам хорошего дня и успехов в дальнейшем обучении**! 🐈

2023-03-05 15:29 UTC, randomroot commented on src/components/OrderListElement/OrderListElement.tsx
> +    const AmountIngredients = orderingredients.slice(
🟡 **Можно улучшить:**

Наименования переменных следует привести к виду `camelCase`

2023-03-15 11:42 UTC, merged